Repository LikeLion12-SMU-Team7/Team7-Front, pull requests merged in 2024-08, with the labels that each got.

#26 💄 style: 화면 리사이징 및 css 수정
  css/home.css
  home.html
  img/chicken.png
  img/meal.png
  img/tanghulu.png
Labels: bug

#30 ✨ feat: 흑역사 작성 시 날짜 선택 기능 추가
  css/darkRecordDetail.css
  darkRecordWriting.html
  js/darkRecordWriting.js
Labels: feat

#32 ✨feat/#31 로그인 token, cookie
  js/index.js
Labels: feat

#27 ✨feat:18 html css js(약간) drinkRecord
  .DS_Store
  css/drinkRecord.css
  drinkRecord.html
  img/sake.png
  img/수정.png
  js/drinkRecord.js
Labels: feat

#28 feat/#22 회원가입 js
  js/register3.js
  js/register4.js
  js/registerFinal.js
  register3.html
  register4.html
Labels: feat

#41 feat:유저 프로필 수정
  js/setting.js
  setting.html
Labels: feat

#40 fix: 이메일 중복성 검사
  js/register1.js
Labels: bug

#51 register1.js 수정
  js/register1.js
Labels: bug

#55 js, html 약간 수정
  AIReport.html
  css/AIReport.css
  js/AIReport.js
Labels: bug, feat

#57 fix: 로그아웃 버튼, 회원가입 후 index
  js/registerFinal.js
  js/setting.js
Labels: bug

#60 fix: id=nickname 추가
  AIReport.html
Labels: bug

#66 fix: btn, kg, 병, 보더박스 수정
  css/setting.css
  js/setting.js
  setting.html
Labels: bug, feat

#64 fix: 이메일 중복검사 오류
  js/register1.js
Labels: bug

#62 fix: previous, new js
  AIReport.html
  css/AIReport.css
  js/AIReport.js
Labels: bug

#81 :sparkles: feat: Markdown.js 파일 추가
  js/markdown.js
Labels: feat

#82 fix73: Aireport + html 틀
  css/AIReport.css
  css/index.css
  index.html
  js/AIReport.js
Labels: bug, feat

#86 fix: nav 수정
  AIReport.html
  setting.html
Labels: bug

#94 fix85: setting 수정
  css/setting.css
  js/setting.js
  setting.html
Labels: bug

#97 Fix95: aireport
  AIReport.html
  css/AIReport.css
  css/setting.css
  js/AIReport.js
  js/setting.js
  setting.html
Labels: bug
